# Generated by Django 2.2.5 on 2020-04-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('stars', models.CharField(max_length=100)),
                ('review_count', models.CharField(max_length=100)),
                ('is_open', models.CharField(max_length=100)),
                ('attributes', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=100)),
                ('hours', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'business',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categorie', models.CharField(blank=True, max_length=200, null=True)),
                ('categorie', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Categorie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DfReview_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('business_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stars', models.CharField(blank=True, max_length=100, null=True)),
                ('mean', models.CharField(blank=True, max_length=100, null=True)),
                ('mark', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'DfReview_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DfReview_train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('business_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stars', models.CharField(blank=True, max_length=100, null=True)),
                ('mean', models.CharField(blank=True, max_length=100, null=True)),
                ('mark', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'DfReview_train',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document_features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_busines', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('id_categorie', models.CharField(blank=True, max_length=200, null=True)),
                ('categorie', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Document_features',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('business_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mark', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Prediction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('business_id', models.CharField(max_length=100)),
                ('stars', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('useful', models.CharField(max_length=100)),
                ('funny', models.CharField(max_length=100)),
                ('cool', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=100)),
                ('compliment_count', models.CharField(max_length=100)),
                ('business_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('review_count', models.CharField(max_length=100)),
                ('yelping_since', models.CharField(max_length=100)),
                ('friends', models.CharField(max_length=100)),
                ('useful', models.CharField(max_length=100)),
                ('funny', models.CharField(max_length=100)),
                ('cool', models.CharField(max_length=100)),
                ('fans', models.CharField(max_length=100)),
                ('elite', models.CharField(max_length=100)),
                ('average_stars', models.CharField(max_length=100)),
                ('compliment_hot', models.CharField(max_length=100)),
                ('compliment_more', models.CharField(max_length=100)),
                ('compliment_profile', models.CharField(max_length=100)),
                ('compliment_cute', models.CharField(max_length=100)),
                ('compliment_list', models.CharField(max_length=100)),
                ('compliment_note', models.CharField(max_length=100)),
                ('compliment_plain', models.CharField(max_length=100)),
                ('compliment_cool', models.CharField(max_length=100)),
                ('compliment_funny', models.CharField(max_length=100)),
                ('compliment_writer', models.CharField(max_length=100)),
                ('compliment_photos', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'userData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PREDICTION_CHART',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(blank=True, max_length=100, null=True)),
                ('artistId', models.CharField(blank=True, max_length=200, null=True)),
                ('prediction', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('musicbrainzArtistId', models.CharField(blank=True, max_length=100, null=True)),
                ('artistName', models.CharField(blank=True, max_length=100, null=True)),
                ('musicbrainzTrackId', models.CharField(blank=True, max_length=100, null=True)),
                ('trackName', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
